services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
      MINIO_VOLUMES: /data
      MINIO_API_SELECT_PARQUET: "on"
    command: server /data --console-address ":9001"
    ports:
      - "9002:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - taxi-network
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9000/minio/health/live || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  polaris:
    container_name: polaris
    image: apache/polaris:1.4.0
    ports:
      - "8183:8181"
      - "8182:8182"
    networks:
      - taxi-network
      # - local-iceberg-lakehouse
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: dummy-region
      AWS_ENDPOINT_URL_S3: http://minio:9002
      AWS_ENDPOINT_URL_STS: http://minio:9002
      POLARIS_BOOTSTRAP_CREDENTIALS: default-realm,root,secret
      polaris.features.DROP_WITH_PURGE_ENABLED: true # allow dropping tables from the SQL client
      polaris.realm-context.realms: default-realm
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8182/healthcheck"]
      interval: 5s
      timeout: 10s
      retries: 5

  minio-client:
    container_name: minio-client
    image: minio/mc:latest
    depends_on:
      - minio
    networks:
      - taxi-network
      # - local-iceberg-lakehouse
    volumes:
      - /tmp:/tmp
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: dummy-region
    entrypoint: >
      /bin/sh -c "
      until (mc alias set minio http://minio:9000 ${MINIO_ROOT_USER:-minioadmin} ${MINIO_ROOT_PASSWORD:-minioadmin}) do echo '...waiting...' && sleep 1; done;
      mc rm -r --force minio/warehouse;
      mc mb minio/warehouse;
      mc anonymous set public minio/warehouse;
      echo 'MinIO client setup complete.';
      "

networks:
  taxi-network:
    # driver: bridge
    external: true

volumes:
  minio-data:

