coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8082
discovery.uri=http://localhost:8082

# Spill
spill-enabled=false
 
# Task concurrency
task.concurrency=4
task.max-worker-threads=8